# Generated by Django 4.1.3 on 2022-11-30 00:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('hotel', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('tour', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='locations')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
