# Generated by Django 4.1.3 on 2022-11-30 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_package_delete_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='hotel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='tour',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
