# Generated by Django 4.1.3 on 2022-11-30 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_package_city_alter_package_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
