# Generated by Django 4.1.3 on 2022-12-03 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_package_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
