# Generated by Django 4.1.3 on 2022-12-03 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_delete_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={},
        ),
    ]
