# Generated by Django 4.1.3 on 2022-12-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_hotel_tour_alter_package_options_remove_package_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='current_room_capacity',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='max_room_capacity',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
