# Generated by Django 4.1.3 on 2022-12-03 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_package_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
