# Generated by Django 4.1.3 on 2022-12-10 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='destination',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
